-- MySQL Script generated by MySQL Workbench
-- Sat Mar 27 12:13:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema pokladna
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pokladna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokladna` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci;
USE `pokladna`;
-- -----------------------------------------------------
-- Table `pokladna`.`objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`objednavky` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `celkovaCena` DECIMAL(6, 2) NULL,
    `casObjednavky` DATETIME NULL,
    PRIMARY KEY (`id`)
);
-- -----------------------------------------------------
-- Table `pokladna`.`pridavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`pridavky` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nazev` VARCHAR(45) NULL,
    `cena` DECIMAL(6, 2) NULL,
    `nadrazeny_id` INT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`nadrazeny_id`) REFERENCES `pokladna`.`pridavky` (`id`)
);
-- -----------------------------------------------------
-- Table `pokladna`.`polozky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`polozky` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nazev` VARCHAR(45) NULL,
    `cena` DECIMAL(6, 2) NULL,
    PRIMARY KEY (`id`)
);
-- -----------------------------------------------------
-- Table `pokladna`.`polozkyvobjednavce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`polozkyvobjednavce` (
    `objednavky_id` INT NOT NULL,
    `polozky_id` INT NOT NULL,
    `mnozstvi` INT NOT NULL,
    PRIMARY KEY (`objednavky_id`, `polozky_id`),
    FOREIGN KEY (`objednavky_id`) REFERENCES `pokladna`.`objednavky` (`id`),
    FOREIGN KEY (`polozky_id`) REFERENCES `pokladna`.`polozky` (`id`)
);
-- -----------------------------------------------------
-- Table `pokladna`.`pridavkyvpolozce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`pridavkyvpolozce` (
    `polozky_id` INT NOT NULL,
    `pridavky_id` INT NOT NULL,
    PRIMARY KEY (`polozky_id`, `pridavky_id`),
    FOREIGN KEY (`polozky_id`) REFERENCES `pokladna`.`polozky` (`id`),
    FOREIGN KEY (`pridavky_id`) REFERENCES `pokladna`.`pridavky` (`id`)
);

INSERT INTO objednavky (celkovaCena, casObjednavky)
VALUES 
(55, "2021-03-27 13:04:55"),
(65, "2021-03-27 13:05:15"),
(70, "2021-03-27 13:12:25"),
(130, "2021-03-27 13:40:30"),
(22, "2021-03-27 13:22:50"),
(125, "2021-03-27 13:15:25");

INSERT INTO polozky (nazev, cena)
VALUES 
("hamburger", 25),
("cheeseburger", 30),
("wrap", 30),
("hranolky", 20);

INSERT INTO pridavky (nazev, cena)
VALUES 
("slanina", 5),
("syr", 3),
("okurek", 2),
("hranolky", 20);

INSERT INTO polozkyvobjednavce (objednavky_id, polozky_id, mnozstvi)
VALUES 
(1, 2, 1),
(1, 1, 8),
(1, 3, 1),
(1, 4, 1),
(2, 2, 1),
(2, 3, 1),
(3, 3, 2),
(4, 3, 3),
(4, 4, 5);

SELECT polozky.nazev, objednavky.id, polozky.id FROM polozky JOIN polozkyvobjednavce ON polozkyvobjednavce.polozky_id=polozky.id JOIN objednavky ON polozkyvobjednavce.objednavky_id=objednavky.id