-- MySQL Script generated by MySQL Workbench
-- Mon Mar 29 13:56:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema pokladna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokladna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokladna` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci;
USE `pokladna`;

-- -----------------------------------------------------
-- Table `pokladna`.`objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`objednavky` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `celkovaCena` DECIMAL(6,2) NULL,
  `casObjednavky` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `pokladna`.`pridavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`pridavky` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `cena` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `pokladna`.`polozky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`polozky` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `cena` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `pokladna`.`polozkyvobjednavce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`polozkyvobjednavce` (
  `objednavky_id` INT NOT NULL,
  `polozky_id` INT NOT NULL,
  `pridavek_id` INT NOT NULL,
  `mnozstvi` INT NOT NULL,
  PRIMARY KEY (`objednavky_id`, `polozky_id`),
    FOREIGN KEY (`objednavky_id`)
    REFERENCES `pokladna`.`objednavky` (`id`),
    FOREIGN KEY (`polozky_id`)
    REFERENCES `pokladna`.`polozky` (`id`));

-- -----------------------------------------------------
-- Table `pokladna`.`pridavkyvpolozce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`pridavkyvpolozce` (
  `polozky_id` INT NOT NULL,
  `pridavky_id` INT NOT NULL,
  PRIMARY KEY (`polozky_id`, `pridavky_id`),
    FOREIGN KEY (`polozky_id`)
    REFERENCES `pokladna`.`polozky` (`id`),
    FOREIGN KEY (`pridavky_id`)
    REFERENCES `pokladna`.`pridavky` (`id`));


-- -----------------------------------------------------
-- Table `pokladna`.`pridavkyvobjednavce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokladna`.`pridavkyvobjednavce` (
  `id_pridavku` INT NOT NULL,
  `pridavek_id` INT NOT NULL,
  PRIMARY KEY (`id_pridavku`, `pridavek_id`),
    FOREIGN KEY (`pridavek_id`)
    REFERENCES `pokladna`.`polozkyvobjednavce` (`pridavek_id`),
    FOREIGN KEY (`id_pridavku`)
    REFERENCES `pokladna`.`pridavky` (`id`));


INSERT INTO objednavky (celkovaCena, casObjednavky)
VALUES 
(55, "2021-03-27 13:04:55"),
(65, "2021-03-27 13:05:15"),
(70, "2021-03-27 13:12:25"),
(130, "2021-03-27 13:40:30"),
(22, "2021-03-27 13:22:50"),
(125, "2021-03-27 13:15:25");

INSERT INTO polozky (nazev, cena)
VALUES 
("hamburger", 25),
("cheeseburger", 30),
("wrap", 30),
("hranolky", 20);

INSERT INTO pridavky (nazev, cena)
VALUES 
("slanina", 5),
("syr", 3),
("okurek", 2),
("hranolky", 20);

INSERT INTO polozkyvobjednavce (objednavky_id, polozky_id, mnozstvi, pridavek_id)
VALUES 
(1, 2, 1, 1),
(1, 1, 8, 2),
(1, 3, 1, 3),
(1, 4, 1, 4),
(2, 2, 1, 5),
(2, 3, 1, 6),
(3, 3, 2, 7),
(4, 3, 3, 8),
(4, 4, 5, 9);


INSERT INTO pridavkyvobjednavce (pridavek_id, id_pridavku)
VALUES 
(1, 2),
(1, 1),
(2, 3),
(2, 4);


INSERT INTO pridavkyvpolozce (polozky_id, pridavky_id)
VALUES 
(1, 1),
(2, 2),
(3, 3),
(4, 4);

SELECT objednavky.id, polozkyvobjednavce.polozky_id, polozky.nazev, polozkyvobjednavce.pridavek_id, pridavky.nazev FROM objednavky JOIN polozkyvobjednavce ON polozkyvobjednavce.objednavky_id=objednavky.id JOIN polozky ON polozkyvobjednavce.polozky_id=polozky.id LEFT JOIN pridavkyvobjednavce ON polozkyvobjednavce.pridavek_id = pridavkyvobjednavce.pridavek_id LEFT JOIN pridavky ON pridavkyvobjednavce.id_pridavku = pridavky.id;

SELECT objednavky.id, polozkyvobjednavce.polozky_id, polozky.nazev, polozkyvobjednavce.pridavek_id FROM objednavky JOIN polozkyvobjednavce ON polozkyvobjednavce.objednavky_id=objednavky.id JOIN polozky ON polozkyvobjednavce.polozky_id=polozky.id LEFT JOIN pridavkyvobjednavce ON polozkyvobjednavce.pridavek_id = pridavkyvobjednavce.pridavek_id LEFT JOIN pridavky ON pridavkyvobjednavce.id_pridavku = pridavky.id GROUP BY polozkyvobjednavce.pridavek_id, polozkyvobjednavce.polozky_id