package pokladna;
import java.awt.GridLayout;
import java.awt.event.*;
import java.util.LinkedList;

import javax.swing.*;

public class MainFrame extends JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    // End of variables declaration

    LinkedList<LinkedList> uloziste = new LinkedList<LinkedList>();

    public static void main(String[] args) {

        JFrame frame = new JFrame("Objednávka");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLayout(new GridLayout(1, 1, 20, 20));
        frame.setResizable(false);

        JButton b = new JButton("Nová objednávka");// creating instance of JButton
        // b.setBounds(130, 100, 100, 40);// x axis, y axis, width, height
        b.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ObjednavkaFrame oframe = new ObjednavkaFrame();
                oframe.setVisible(true);

            } 
        });
        frame.add(b);// adding button in JFrame

        JButton vypsat = new JButton("Vypsat objednávku");// creating instance of JButton
        // vypsat.setBounds(130, 100, 100, 40);// x axis, y axis, width, height

        vypsat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VypisFrame v = new VypisFrame();
                v.setVisible(true);
            }
        });
        frame.add(vypsat);// adding button in JFrame

        JButton end = new JButton("Konec");
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });
        // creating instance of JButton
        // vypsat.setBounds(130, 100, 100, 40);// x axis, y axis, width, height
        frame.add(end);// adding button in JFrame

        frame.setSize(560, 200);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

}
